name: Handle docs commit from repo-emitter

on:
  repository_dispatch:
    types: [docs-commit]

jobs:
  respond-to-docs-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: echo "Repo reported a docs commit!"
      - name: Get commit message from client_payload
        id: get_payload
        run: |
          echo "commit_msg=${{ github.event.client_payload.commit_msg }}" >> $GITHUB_OUTPUT
