name: Handle docs commit from repo-emitter

on:
  repository_dispatch:
    types: [docs-commit]

jobs:
  respond-to-docs-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: echo "Repo reported a docs commit!"
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - name: Get commit message from client_payload
        id: get_payload
        run: |
          echo "commit_msg=${{ github.event.client_payload.commit_msg }}" >> $GITHUB_OUTPUT
      - name: Write commit into CHANGELOG.md
        run: |
          echo "" >> CHANGELOG.md
          echo "---" >> CHANGELOG.md
          echo "${{ steps.get_payload.outputs.commit_msg }}" >> CHANGELOG.md
          echo "Updated on: $(date)" >> CHANGELOG.md
      - name: Commit and push changes
        run: |
          # TODO: Actually have to pass user name etc
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add CHANGELOG.md
          git commit -m "Docs update from emitter: ${{ steps.get_payload.outputs.commit_msg }}" || echo "No changes to commit"
          git push